import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ListpaysService {
all_pays=[
 
"Île de Man",
"Croatie",
  "Guinée-Bissau",
"Inde",
"Kenya",
"Laos",
"Territoire britannique de l'océan Indien",
"Haïti",
"Liban",
"Guyana",
"Kirghizistan",
"Hongrie",
"Sainte-Lucie",
"Irak",
"Cambodge",
"Jamaïque",
"Iran",
"Kiribati",
"Islande",
"Maroc",
"Jordanie",
"Italie",
"Japon",
"Monaco",
"Comores",
"Moldavie",
"Liechtenstein",
"Saint-Christophe-et-Niévès",
"Monténégro",
"Namibie",
"Saint-Martin",
"Sri Lanka",
"Corée du Nord",
"Madagascar",
"Nouvelle-Calédonie",
"Îles Marshall",
"Corée du Sud",
"Niger",
"Île Norfolk",
"Macédoine",
"Nigéria",
"Mali",
"Myanmar (Birmanie)",
"Libéria",
"Nicaragua",
"Koweït",
"Mongolie",
"Lesotho",
"Panamá",
"Macau",
"Lituanie",
"Îles Caïmans",
"Îles Mariannes du Nord",
"Luxembourg",
"Pays-Bas",
"Kazakhstan",
"Martinique",
"Lettonie",
"Mauritanie",
"Pérou",
"Montserrat",
"Qatar",
"Norvège",
"Tahïti (Polynésie française)",
"Malte",
"Libye",
"Népal",
"Papouasie-Nouvelle-Guinée",
"Maurice", "Philippines",
"Maldives",
"Oman",
"Nauru",
"Malawi",
"Mexico",
"Pakistan",
"Malaisie",
"Niue",
"Pologne",
"Mozambique",
"Saint-Pierre-et-Miquelon",
"Îles Pitcairn",
"La Réunion",
"Arabie saoudite",
"Îles Salomon",
"Nouvelle-Zélande",
"Seychelles",
"Soudan",
"Porto Rico",
"Suède",
"Territoires palestiniens occupés",
"Portugal",
"Singapour",
"Îles Turques-et-Caïques",
"Sainte-Hélène",
"Tchad",
"Slovénie",
"Palaos",
"Svalbard et Jan Mayen",
"Ukraine",
"Roumanie",
"Terres australes et antarctiques françaises",
"Slovaquie",
"Paraguay",
"Togo",
"Sierra Leone",
"Thaïlande",
"Saint-Marin",
"Sénégal",
"Serbie (Yougoslavie)",
"Tadjikistan",
"Cité du Vatican",
"Somalie",
"Tokelau",
"Ouganda",
"Russie",
"Timor oriental",
"Saint-Vincent-et-les-Grenadines",
"Turkménistan",
"Suriname",
"Rwanda",
"Tunisie",
"Venezuela",
"Tonga",
"Sao Tomé-et-Principe",
"Îles Vierges britanniques",
"Salvador",
"Îles mineures éloignées des États-Unis",
"Turquie",
"Îles Vierges(US)",
"Wallis-et-Futuna",
"Trinité-et-Tobago",
"Syrie",
"Swaziland",
"Tuvalu",
"Taïwan",
"Viêt Nam",
"États-Unis(USA)",
"Tanzanie",
"Yémen",
"Afrique du Sud",
"République du Kosovo",
"Uruguay",
"Vanuatu",
"Ouzbékistan",
"Samoa",
"Zambie",
"Île de l'Ascension",
"Andorre",
"Mayotte",
"Émirats arabes unis",
"Serbia and Montenegro",
"Serbie-et-Monténégro",
"Afghanistan",
"Barbade",
"Antigua-et-Barbuda",
"Bangladesh",
"Anguilla",
"Belgique",
"Canada",
"Burkina Faso",
"Bulgarie",
"Zimbabwe",
"Albanie",
"Îles Cocos",
"Bahreïn",
"Arménie",
"République démocratique du Congo",
"Burundi",
"Antilles néerlandaises",
"Bénin",
"Angola",
"République centrafricaine",
"République du Congo",
"Antarctique",
"Suisse",
"Bermudes",
"Argentine",
"Côte d'Ivoire",
"Brunei Darussalam",
"Allemagne",
"Samoa américaines",
"Bolivie",
"Autriche",
"Îles Cook",
"Australie",
"Chili",
"Équateur",
"Cameroun",
"Brésil",
"Aruba",
"Chine",
"Estonie",
"Bahamas",
"Djibouti",
"Åland",
"Colombie",
"Bhoutan",
"Danemark",
"Égypte",
"Azerbaïdjan",
"Sahara occidental",
"Île Bouvet",
"Dominique",
"Costa Rica",
"Botswana",
"Gabon",
"République dominicaine",
"Biélorussie",
"Royaume-Uni",
"Cuba",
"Bélize",
"Cap-Vert",
"Grenade",
"Finlande",
"Géorgie",
"Fidji",
"Île Christmas",
"Guyane",
"Îles Malouines",
"Chypre",
"Guernesey",
"République tchèque",
"Ghana",
"Micronésie",
"Érythrée",
"Gibraltar",
"Espagne",
"Îles Féroé",
"Éthiopie",
"Groenland",
"Algérie",
"Gambie",
"Indonésie",
"France",
"Guinée",
"Irlande",
"Hong Kong",
"Guadeloupe",
"Guinée équatoriale",
"Îles Heard-et-MacDonald",
"Grèce",
"Honduras",
"Jersey",
"Géorgie du Sud-et-les Îles Sandwich du Sud",
"France métropolitaine",
"Guatemala",
"Guam",
"Israël"]
  constructor() { }
  getlistpays(){
    return this.all_pays
    
  }
}
